// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVX2XgT4eEKurl9L2Fr7XH0_DfTlMPil4',
    appId: '1:771079273145:web:cc49605dbafa0b89a57968',
    messagingSenderId: '771079273145',
    projectId: 'e-commerce-f5b0b',
    authDomain: 'e-commerce-f5b0b.firebaseapp.com',
    storageBucket: 'e-commerce-f5b0b.firebasestorage.app',
    measurementId: 'G-EY2Q6FGWNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsrEYpGto_TIiiIIuCNXyRAbmR4Qv_SdY',
    appId: '1:771079273145:android:dc3e218348b9b2caa57968',
    messagingSenderId: '771079273145',
    projectId: 'e-commerce-f5b0b',
    storageBucket: 'e-commerce-f5b0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI4i2q-w-LK1IA1de8jOkriFu0eGXiBLQ',
    appId: '1:771079273145:ios:2a45025313dd835ca57968',
    messagingSenderId: '771079273145',
    projectId: 'e-commerce-f5b0b',
    storageBucket: 'e-commerce-f5b0b.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI4i2q-w-LK1IA1de8jOkriFu0eGXiBLQ',
    appId: '1:771079273145:ios:2a45025313dd835ca57968',
    messagingSenderId: '771079273145',
    projectId: 'e-commerce-f5b0b',
    storageBucket: 'e-commerce-f5b0b.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

}